<a href="https://colab.research.google.com/github/DeepSmeag/ML_Colab/blob/main/AND%2BXORperceptrons.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!git clone https://github.com/DeepSmeag/ML_Colab

fatal: destination path 'ML_Colab' already exists and is not an empty directory.


First we load the project so we get access to the files. Then we read the files of interest

In [3]:
def read_file(file_path):
  dataset=[]
  with open(file_path, 'r') as f:
    lines = f.readlines()
    for line in lines:
      line = line.strip()
      parts = line.split(',')
      x0,x1,y1,y2 = float(parts[0]), float(parts[1]), float(parts[2]), float(parts[3])
      dataset.append((x0,x1,y1,y2))
    return dataset

dataset = read_file('ML_Colab/datasetAND+XOR.csv')
"""it could also work with numpy and/or pandas to read the whole csv file at the
same time, probably more efficient too
"""


'it could also work with numpy and/or pandas to read the whole csv file at the\nsame time, probably more efficient too\n'

We now have our dataset ready for use, next let's go and make the vectors for use with our network

In [4]:
import numpy as np
import csv
import pandas

In [73]:
#first layer is input, meaning we take the first 2 columns of the dataset
num_trains = len(dataset)
X = np.array(dataset)[:,0:2]
#now we add the bias to every training instance
X = np.append(X, np.ones((num_trains,1)), axis=1)
# now we take the outputs
Y = np.array(dataset)[:,2:4]

In [102]:
#now we create Numpy arrays so that we have our weights
#the first layer
W1 = np.random.uniform(-1,1,(3,3))
#the second
W2 = np.random.uniform(-1,1,(4,2))
print("W1:\n",W1,"\n")
print("W2:\n",W2,"\n")

W1:
 [[ 0.93014127 -0.23880296 -0.0947628 ]
 [-0.75176898  0.46879779  0.37658056]
 [-0.25108595 -0.94993341  0.13504216]] 

W2:
 [[ 0.39763269  0.02257951]
 [ 0.72728249  0.72361378]
 [ 0.51985589 -0.90214578]
 [-0.02184104 -0.82756651]] 



In [110]:
#Now we're getting to the fun stuff
#First, defining the necessary functions

def sigmoid(x):
  return 1/(1 + np.exp(-x))

#Forward Propagation
def forward_prop(X, W1, W2):
  #calculating the steps
  z2 = np.matmul(X, W1)
  a2 = sigmoid(z2)
  a2 = np.insert(a2, 3, np.ones((num_trains,)), axis = 1)
  z3 = np.matmul(a2, W2)
  y_hat = sigmoid(z3)
  return z2, a2, z3, y_hat



In [134]:
#Ok, so that was forward propagation
#Now, the NN should also be able to learn, so we have to implement Backprop
#Since we're guessing at best at the moment as to the correct outputs
#We have to define several functions for Backprop to work
#These include the partial derivatives with which we'll update the weights matrices W1 and W2
#And also the backprop itself which will go over epochs or whatever we may call it

# matrices sizes
# X = num_trains x 3
# W1 = 3 x 3
# Z2 = num_trains x 3
# A2 = num_trains x 4 by adding a collumn of ones at the end
# W2 = 4 x 2
# Z3 = num_trains x 2
# A3 = Y_hat = num_trains x 2


def sigmoid_gradient(x):
  return np.multiply(sigmoid(x),(1-sigmoid(x)))
def derivative(z2, a2, z3, y_hat, training_point):
  dz3 = sigmoid_gradient(z3[training_point, :]) # 1 x 2
  dw2 = np.matmul(np.matrix(a2[training_point, :]).T, np.matrix(dz3)) # 4 x 2
  dz2 = np.matrix(sigmoid_gradient(z2[training_point, :])) # 1 x 3

  
  

  da2 = np.matmul(dz3, W2.transpose()) # 1 x 4
  da2 = np.delete(da2, 3) # drop last column because it's for bias, 1 x 3

  temp1 = np.multiply(da2, dz2) # 1 x 3
  
  dw1 = np.matmul(np.matrix(X[training_point, :]).T, temp1) # 3 x 3
  return dw1, dw2

def backprop(num_trains, learning_rate, input, weights1, weights2):
  global X, W1, W2
  z2, a2, z3, y_hat = forward_prop(X, W1, W2)
  for training_point in range(num_trains):
    print("current_training_point: ", training_point+1, "\n")
    
    dw1, dw2 = derivative(z2, a2, z3, y_hat, training_point)
    print(W1)
    W1 = np.subtract(W1, learning_rate * dw1)
    W2 = np.subtract(W2, learning_rate * dw2)
    error = np.power((y_hat - Y[training_point, :]), 2)
    error = np.sum(error)
    print("error:", error)
  with open("ML_Colab/AND+XORmodelW1.csv", 'w') as fw1:
    np.savetxt(fw1 , W1 , fmt='%s', delimiter=',')
  with open("ML_Colab/AND+XORmodelW2.csv", 'w') as fw2:
    np.savetxt(fw2 , W2 , fmt='%s', delimiter=',')

backprop(num_trains, 10, X, W1, W2)

Datele de ieșire de afișat au fost trunchiate la ultimele 5000 linii.
 [ 1.26712627 -1.17423514  2.06656899]]
error: 999.8525008586175
current_training_point:  168 

[[ 1.47632189 -0.35961987  0.69957196]
 [-0.00496861  0.34404631  1.13910644]
 [ 1.26729963 -1.17416002  2.06681747]]
error: 999.839208424957
current_training_point:  169 

[[ 1.47647673 -0.35954034  0.69964776]
 [-0.00481378  0.34412584  1.13918224]
 [ 1.26745446 -1.17408048  2.06689327]]
error: 1.2653323887945454e-05
current_training_point:  170 

[[ 1.47647673 -0.35954034  0.69964776]
 [-0.00481378  0.34412584  1.13918224]
 [ 1.26828738 -1.17392713  2.06761653]]
error: 999.8525008586175
current_training_point:  171 

[[ 1.47647673 -0.35954034  0.69964776]
 [-0.00415203  0.34426638  1.13939711]
 [ 1.26894912 -1.17378659  2.0678314 ]]
error: 999.8525008586175
current_training_point:  172 

[[ 1.47665029 -0.35946508  0.69989646]
 [-0.00415203  0.34426638  1.13939711]
 [ 1.26912268 -1.17371133  2.0680801 ]]
error: 999.83920

In [135]:
new_w1 = np.genfromtxt('ML_Colab/AND+XORmodelW1.csv', delimiter=',')

new_w2 = np.genfromtxt('ML_Colab/AND+XORmodelW2.csv', delimiter=',')

Null, Null, Null, y_hat = forward_prop(X, new_w1, new_w2)
y_hat = np.rint(y_hat)
print(y_hat)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [79]:
Y

array([[0., 0.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [1., 0.]])